---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, .gitattributes]
permalink: /:title ## disables post output
timezone: America/Los_Angeles
lsi: false
markdown: kramdown
include:
  - "_docfx"

### content configuration ###
title:       "Marymoor Studios"
keywords:    "marymoorstudios, gaming, promises"
description: "Marymoor Studios is a video game design startup."
source_link: "https://github.com/MarymoorStudios/marymoorstudios.github.io"
favicon:     "img/logo.svg"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  true

collections:
  front_pages:
    output: true
    sort_by: order
  devlog:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "devlog"
    values:
      layout: "default"
